# ===========================================================================
# Cloud SQL (PostgreSQL) — durable A2A task store for both agents
# ---------------------------------------------------------------------------
# The a2a-sdk DefaultRequestHandler persists Task objects here (DatabaseTaskStore)
# instead of InMemoryTaskStore, so tasks survive Cloud Run restarts / redeploys and
# are shared across instances (no longer lost on scale-to-zero or a new revision).
#
# Both agent services (kga + tpd) mount the Cloud SQL Auth proxy socket and share ONE
# instance + ONE database; task ids are UUIDs so a shared `tasks` table is
# collision-free. The two A2A->MCP bridges are stateless MCP clients and do NOT touch
# the DB. Toggle the whole thing with `deploy_cloudsql`.
#
# Reachability: the instance keeps a public IP with NO authorized networks, so nothing
# can connect over raw IP. Cloud Run reaches it only through the Cloud SQL Auth proxy
# (IAM-authenticated + encrypted), mounted as a unix socket at /cloudsql/<conn>. The
# runtime SA (google_service_account.kga, shared by both agents) gets roles/cloudsql.client.
# ===========================================================================

variable "deploy_cloudsql" {
  type        = bool
  description = "Provision the v2 stack's OWN Cloud SQL Postgres instance and wire the agents to it (durable DatabaseSessionService). Default ON: v2 runs its own instance, isolated from v1 (extra cost — the two stacks do NOT share a DB). Set false to fall back to in-memory sessions/tasks (the GCS memory bank stays durable regardless)."
  default     = true
}

variable "db_instance_name" {
  type        = string
  description = "Cloud SQL instance name."
  default     = "kga-taskstore"
}

variable "db_tier" {
  type        = string
  description = "Cloud SQL machine tier. db-f1-micro = cheapest shared-core (dev)."
  default     = "db-f1-micro"
}

variable "db_version" {
  type        = string
  description = "Cloud SQL Postgres engine version."
  default     = "POSTGRES_16"
}

variable "db_name" {
  type        = string
  description = "Database that holds the A2A `tasks` table."
  default     = "taskstore"
}

variable "db_user" {
  type        = string
  description = "Postgres login role the agents connect as."
  default     = "taskstore"
}

variable "db_deletion_protection" {
  type        = bool
  description = "Guard the instance against terraform destroy. false for dev."
  default     = false
}

# ---------------------------------------------------------------------------
# Instance + database + login role
# ---------------------------------------------------------------------------
resource "google_sql_database_instance" "taskstore" {
  count               = var.deploy_cloudsql ? 1 : 0
  name                = var.db_instance_name
  region              = var.region
  database_version    = var.db_version
  deletion_protection = var.db_deletion_protection

  settings {
    # db-f1-micro (shared-core) is only valid under ENTERPRISE edition; new instances
    # otherwise default to ENTERPRISE_PLUS, which rejects it (needs db-perf-optimized-N-*).
    edition           = "ENTERPRISE"
    tier              = var.db_tier
    availability_type = "ZONAL" # dev: single zone, no HA
    disk_type         = "PD_SSD"
    disk_size         = 10
    disk_autoresize   = true

    backup_configuration {
      enabled = true
    }

    ip_configuration {
      ipv4_enabled = true
      # No authorized_networks: the instance is reachable ONLY through the Cloud SQL
      # Auth proxy (IAM + TLS), which Cloud Run mounts as a unix socket. The public IP
      # exists so the managed proxy can dial it; raw IP connections are rejected.
    }
  }

  depends_on = [google_project_service.apis]
}

resource "google_sql_database" "taskstore" {
  count    = var.deploy_cloudsql ? 1 : 0
  name     = var.db_name
  instance = google_sql_database_instance.taskstore[0].name
}

resource "random_password" "db" {
  count            = var.deploy_cloudsql ? 1 : 0
  length           = 32
  special          = true
  override_special = "_%+=:.-" # URL/socket-safe subset (avoids @ / # ? & that complicate URLs)
}

resource "google_sql_user" "taskstore" {
  count    = var.deploy_cloudsql ? 1 : 0
  name     = var.db_user
  instance = google_sql_database_instance.taskstore[0].name
  password = random_password.db[0].result
}

# ---------------------------------------------------------------------------
# DB password in Secret Manager
# ---------------------------------------------------------------------------
# Unlike the app bearer / atlassian secrets (whose VALUES are added out-of-band by
# deploy.sh), this password is GENERATED by terraform, so terraform manages the
# version too. Cloud Run mounts it as the DB_PASSWORD env var.
resource "google_secret_manager_secret" "db_password" {
  count     = var.deploy_cloudsql ? 1 : 0
  secret_id = "${var.name_prefix}-db-password"
  replication {
    auto {}
  }
  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "db_password" {
  count       = var.deploy_cloudsql ? 1 : 0
  secret      = google_secret_manager_secret.db_password[0].id
  secret_data = random_password.db[0].result
}

# ---------------------------------------------------------------------------
# IAM — the shared agent runtime SA can connect + read the password
# ---------------------------------------------------------------------------
resource "google_project_iam_member" "cloudsql_client" {
  count   = var.deploy_cloudsql ? 1 : 0
  project = var.project_id
  role    = "roles/cloudsql.client"
  member  = "serviceAccount:${google_service_account.kga.email}"
}

resource "google_secret_manager_secret_iam_member" "db_password_access" {
  count     = var.deploy_cloudsql ? 1 : 0
  secret_id = google_secret_manager_secret.db_password[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.kga.email}"
}

# ---------------------------------------------------------------------------
# Shared wiring consumed by the agent services (main.tf, test-plan-definition.tf)
# ---------------------------------------------------------------------------
locals {
  cloudsql_connection_name = var.deploy_cloudsql ? google_sql_database_instance.taskstore[0].connection_name : ""

  # Plain (non-secret) env injected into each agent container when Cloud SQL is on.
  # The password is added separately via a secret_key_ref. common.build_task_store()
  # assembles the asyncpg URL from these:
  #   postgresql+asyncpg://DB_USER:DB_PASSWORD@/DB_NAME?host=/cloudsql/DB_INSTANCE_CONNECTION_NAME
  cloudsql_env = var.deploy_cloudsql ? {
    DB_INSTANCE_CONNECTION_NAME = local.cloudsql_connection_name
    DB_USER                     = var.db_user
    DB_NAME                     = var.db_name
  } : {}

  # Two-tier memory (pgvector recall) env, injected into every agent container. Harmless under the
  # default MEMORY_BACKEND=gcs (the code reads the DB / embeds only when the backend is hybrid or
  # postgres), so it needs no gating and a runtime flip is just a tfvars change + apply.
  memory_env = [
    { name = "MEMORY_BACKEND", value = var.memory_backend },
    { name = "MEMORY_EMBED_MODEL", value = var.memory_embed_model },
    { name = "MEMORY_EMBED_DIMS", value = var.memory_embed_dims },
    { name = "MEMORY_EMBED_LOCATION", value = var.memory_embed_location },
    { name = "MEMORY_DRAIN_BUDGET_S", value = var.memory_drain_budget_s },
    { name = "MEMORY_SEMANTIC_SEED", value = var.memory_semantic_seed },
  ]
}
