#!/usr/bin/env bash
# Deploy the Testing Agent stack (first-deploy-safe order):
#   secret containers + versions  →  artifact repo  →  BUILD image  →  full terraform apply.
# The image is built BEFORE the services because the containers override the entrypoint to run
# uvicorn/the bridge — the `hello` placeholder can't boot, so services need a real image up front.
# Covers all three A2A agents (knowledge-gathering, test-plan-definition, test-evaluation) + the
# single MCP gateway (mcp-gateway-v2) — one shared image, one shared bucket.
#
# Usage:
#   ./deploy.sh                 # full deploy (build + apply)
#   SKIP_BUILD=1 ./deploy.sh    # skip the build; apply with the image in tfvars/env/state
#   IMAGE=<ref> ./deploy.sh     # override the image tag
#   PLAN=1 ./deploy.sh          # terraform plan only, change nothing
#
# Robust build: uses `gcloud builds submit --async` + polls `builds describe`, so the
# "can only stream logs if Viewer/Owner" error can't fail a build that actually SUCCEEDS.
#
# Secrets are read from ../../test-agent-v2/.env (ATLASSIAN_API_TOKEN, A2A_BEARER_TOKEN,
# GATEWAY_BEARER_TOKEN) or the current shell env. The Cloud SQL DB
# password is generated by terraform (not here). Requires: terraform, gcloud (ADC), terraform.tfvars.
set -euo pipefail
cd "$(dirname "$0")"

command -v terraform >/dev/null || { echo "terraform not on PATH"; exit 1; }
command -v gcloud   >/dev/null || { echo "gcloud not on PATH"; exit 1; }
[ -f terraform.tfvars ] || { echo "terraform.tfvars missing (copy terraform.tfvars.example)"; exit 1; }

# Load secrets from the app .env if present (non-fatal if absent).
ENV_FILE="../../test-agent-v2/.env"
if [ -f "$ENV_FILE" ]; then
  set -a; . "$ENV_FILE"; set +a
fi

add_secret() {  # <secret-name> <env-var-name> — add a version only if the value is available
  local name="$1" val="${!2:-}"
  if [ -n "$val" ]; then
    printf '%s' "$val" | gcloud secrets versions add "$name" --data-file=- >/dev/null
    echo "    $name: version added"
  else
    echo "    $name: SKIPPED ($2 not set)"
  fi
}

build_and_push() {  # <image> — build via Cloud Build, tolerant of the log-streaming exit-code quirk
  local img="$1" id status
  echo "==> build + push $img (Cloud Build, async + poll)"
  # --async submits and returns immediately WITHOUT trying to stream logs. A synchronous
  # `builds submit` exits non-zero on "can only stream logs if you are Viewer/Owner" even though
  # the build itself SUCCEEDS server-side — so we poll `builds describe` for the real status and
  # only fail on an actual terminal failure.
  id=$(gcloud builds submit ../../test-agent-v2 --tag "$img" --async --format='value(id)')
  [ -n "$id" ] || { echo "ERROR: Cloud Build returned no build id" >&2; return 1; }
  echo "    build id: $id  (console: https://console.cloud.google.com/cloud-build/builds/$id)"
  while true; do
    status=$(gcloud builds describe "$id" --region=global --format='value(status)' 2>/dev/null || true)
    case "$status" in
      SUCCESS)                          echo "    build SUCCESS"; return 0 ;;
      FAILURE|TIMEOUT|CANCELLED|EXPIRED) echo "ERROR: Cloud Build $status — see the console link above" >&2; return 1 ;;
      *)                                sleep 10 ;;  # QUEUED / WORKING / transient-empty describe
    esac
  done
}

echo "==> terraform init"
terraform init -input=false >/dev/null

if [ "${PLAN:-0}" = "1" ]; then
  terraform plan -input=false
  exit 0
fi

# --- secret containers FIRST ---
# A Cloud Run service that mounts `secret:latest` fails to start if the secret has no version
# yet. Since services + their secrets live in one config, create the secret CONTAINERS up front
# (targeted, idempotent) so we can add versions before the services that mount them are created.
echo "==> terraform apply (secret containers)"
terraform apply -auto-approve -input=false \
  -target='google_secret_manager_secret.atlassian_token' \
  -target='google_secret_manager_secret.bitbucket_app_password' \
  -target='google_secret_manager_secret.a2a_bearer' \
  -target='google_secret_manager_secret.gateway_bearer[0]'

echo "==> secret versions"
add_secret kga-v2-atlassian-api-token      ATLASSIAN_API_TOKEN
add_secret kga-v2-bitbucket-app-password   ATLASSIAN_BITBUCKET_APP_PASSWORD
add_secret kga-v2-a2a-bearer-token         A2A_BEARER_TOKEN
add_secret kga-v2-gateway-bearer-token     GATEWAY_BEARER_TOKEN

# --- resolve the image tag (env > tfvars; for SKIP_BUILD, fall back to the deployed image) ---
IMAGE="${IMAGE:-$(awk -F'"' '/^[[:space:]]*image[[:space:]]*=/{print $2; exit}' terraform.tfvars)}"
if [ -z "$IMAGE" ] && [ "${SKIP_BUILD:-0}" = "1" ]; then
  IMAGE=$(terraform state show 'module.kga.google_cloud_run_v2_service.this[0]' 2>/dev/null | awk -F'"' '/^[[:space:]]*image[[:space:]]*=/{print $2; exit}') || true
fi
[ -n "$IMAGE" ] || { echo "ERROR: no image resolved — set 'image' in terraform.tfvars or export IMAGE=" >&2; exit 1; }

# --- ensure the artifact repo exists BEFORE the build pushes to it (first-deploy-safe) ---
echo "==> terraform apply (artifact repo)"
terraform apply -auto-approve -input=false -target='google_artifact_registry_repository.images'

# --- build the image BEFORE creating the services ---
# The Cloud Run containers override the entrypoint to run uvicorn / the bridge, so the `hello`
# placeholder can't boot — the real image must exist before the services are created. (This script
# used to build AFTER an infra apply, which made a true FIRST deploy fail on the placeholder.)
if [ "${SKIP_BUILD:-0}" != "1" ]; then
  build_and_push "$IMAGE"
else
  echo "==> SKIP_BUILD=1 — using existing image: $IMAGE"
fi

# --- single full apply with the real image (creates Cloud SQL + services on a bootable image) ---
# Retry once: on a first apply the terraform-generated db-password secret VERSION can race the
# service that mounts it (the service references the secret container, not the version) — a
# re-apply clears it.
echo "==> terraform apply (image=$IMAGE)"
terraform apply -auto-approve -input=false -var="image=$IMAGE" || {
  echo "==> first apply failed — retrying once (db-password version race / eventual consistency)"
  terraform apply -auto-approve -input=false -var="image=$IMAGE"
}

echo ""
echo "Deployed. Claude connects to the SINGLE MCP gateway (the agents are A2A-only, reached by it):"
echo "  gateway (MCP):  $(terraform output -raw gateway_url 2>/dev/null || echo n/a)"
echo "  agents (A2A):   kga=$(terraform output -raw kga_a2a_url 2>/dev/null || echo n/a)"
echo "                  tpd=$(terraform output -raw tpd_a2a_url 2>/dev/null || echo n/a)"
echo "                  tev=$(terraform output -raw tev_a2a_url 2>/dev/null || echo n/a)"
echo ""
echo "Register the gateway with Claude Code:  ./install-mcp.sh   (Windows: install-mcp.cmd)"
